#ifndef PINOUT_H_INCLUDED
#define PINOUT_H_INCLUDED

// PLL - STuW81300
#define CLK_HIGH GPIOB->BSRR|=GPIO_BSRR_BS6  //PB6
#define CLK_LOW GPIOB->BSRR|=GPIO_BSRR_BR6   //PB6
#define DATA_HIGH GPIOB->BSRR|=GPIO_BSRR_BS7 //PB7
#define DATA_LOW GPIOB->BSRR|=GPIO_BSRR_BR7  //PB7
#define LE_HIGH GPIOB->BSRR|=GPIO_BSRR_BS5   //PB5
#define LE_LOW GPIOB->BSRR|=GPIO_BSRR_BR5    //PB5
#define MUX (GPIOB->IDR & GPIO_IDR_ID8)      //PB8

#define HW_PD_HIGH GPIOA->BSRR|=GPIO_BSRR_BS15     //PA15
#define HW_PD_LOW GPIOA->BSRR|=GPIO_BSRR_BR15      //PA15
#define PDF_RF1_HIGH GPIOB->BSRR|=GPIO_BSRR_BS3    //PB3
#define PDF_RF1_LOW GPIOB->BSRR|=GPIO_BSRR_BR3     //PB3
#define PDF_RF2_HIGH GPIOB->BSRR|=GPIO_BSRR_BS4    //PB4
#define PDF_RF2_LOW GPIOB->BSRR|=GPIO_BSRR_BR4     //PB4

// MAIN System

// RS-232
// PA9, PA10

#endif /* PINOUT_H_INCLUDED */
