#ifndef PINOUT_H_INCLUDED
#define PINOUT_H_INCLUDED

// PLL - MAX2871
#define CLK_HIGH GPIOB->BSRR|=GPIO_BSRR_BS6  //PB6
#define CLK_LOW GPIOB->BSRR|=GPIO_BSRR_BR6   //PB6
#define DATA_HIGH GPIOB->BSRR|=GPIO_BSRR_BS5 //PB5
#define DATA_LOW GPIOB->BSRR|=GPIO_BSRR_BR5  //PB5
#define LE_HIGH GPIOB->BSRR|=GPIO_BSRR_BS4   //PB4
#define LE_LOW GPIOB->BSRR|=GPIO_BSRR_BR4    //PB4
#define RFEN_HIGH GPIOB->BSRR|=GPIO_BSRR_BS3 //PB3
#define RFEN_LOW GPIOB->BSRR|=GPIO_BSRR_BR3  //PB3
#define MUX (GPIOB->IDR & GPIO_IDR_ID7) // PB7

// MAIN System

// RS-232
// PA9, PA10

#endif /* PINOUT_H_INCLUDED */
