#ifndef PINOUT_H_INCLUDED
#define PINOUT_H_INCLUDED

// PLL - LMX2491
#define R_CLK_HIGH GPIOB->BSRR|=GPIO_BSRR_BS7  //PB7
#define R_CLK_LOW GPIOB->BSRR|=GPIO_BSRR_BR7   //PB7
#define R_DATA_HIGH GPIOB->BSRR|=GPIO_BSRR_BS6 //PB6
#define R_DATA_LOW GPIOB->BSRR|=GPIO_BSRR_BR6  //PB6
#define R_LE_HIGH GPIOB->BSRR|=GPIO_BSRR_BS5   //PB5
#define R_LE_LOW GPIOB->BSRR|=GPIO_BSRR_BR5    //PB5
#define R_MUX (GPIOB->IDR & GPIO_IDR_ID4)      //PB4

#define R_TRIG1_HIGH GPIOB->BSRR|=GPIO_BSRR_BS3    //PB3
#define R_TRIG1_LOW GPIOB->BSRR|=GPIO_BSRR_BR3     //PB3

#define R_MOD_HIGH GPIOB->BSRR|=GPIO_BSRR_BS8   //PB8
#define R_MOD_LOW GPIOB->BSRR|=GPIO_BSRR_BR8    //PB8

// MAIN System

// RS-232
// PA9, PA10

#endif /* PINOUT_H_INCLUDED */
