#ifndef PINOUT_H_INCLUDED
#define PINOUT_H_INCLUDED

// ATTEN - F1958
#define aCLK_HIGH GPIOA->BSRR|=GPIO_BSRR_BS_1  //PA1
#define aCLK_LOW GPIOA->BSRR|=GPIO_BSRR_BR_1   //PA1
#define aMOSI_HIGH GPIOA->BSRR|=GPIO_BSRR_BS_2 //PA2
#define aMOSI_LOW GPIOA->BSRR|=GPIO_BSRR_BR_2  //PA2
#define aLE_HIGH GPIOA->BSRR|=GPIO_BSRR_BS_0   //PA0
#define aLE_LOW GPIOA->BSRR|=GPIO_BSRR_BR_0    //PA0

#endif /* PINOUT_H_INCLUDED */
